### PR TITLE
fix Re-subscribing to the channel will result in multiple subscriptions

### PR DESCRIPTION
**Pull request by StanLee12**

### CODE REVIEW

**Comment by FZambia** [comment]
@StanLee12 thanks for report and pull request. Actually the fact that subscriptions left in _subs is OK, there must be alternative fix - could you describe a problem so I could reproduce it?

**Comment by StanLee12** [comment]
@FZambia  First, I unsubscribe a channel, not disconnect  Centrifuge. And I Re-subscribe this channel again, it would be subscribed this channel twice, and client will receive two repeated messages.

**Comment by FZambia** [comment]
@StanLee12 could you show code example? I need to know how exactly you are unsubscribing and subscribing. Do you call `subscribe` method of subscription object to subscribe again?

**Comment by StanLee12** [comment]
```
// connect
this.centrifuge = new Centrifuge(config);
this.centrifuge.connect();

// use this to subscribe and re-subscribe
this.subscription = this.centrifuge.subscribe(channel, callbacks);

// use this to unsubscribe
this.subscription.unsubscribe();
```
Is there any problem with this?

**Comment by FZambia** [comment]
Subscription is an Event Emitter and when you call `centrifuge.subscribe(channel, events)` second time then new events added to subscription second time.

I am not sure how to fix this inside client, but you have 2 options at moment:

First is using `subscribe` method of subscription to subscribe again after unsubscribe:

```javascript
this.subscription = this.centrifuge.subscribe(channel, events);

// use this to unsubscribe
this.subscription.unsubscribe();

// and later
this.subscription.subscribe();
```

And second:

```
this.subscription = this.centrifuge.subscribe(channel, events);

// use this to unsubscribe
subscription.removeAllListeners();
subscription.unsubscribe();

// and later
this.subscription = this.centrifuge.subscribe(channel, events);
```

**Comment by StanLee12** [comment]
Thanks for your answer! I know the problem.   I will close this pr and thanks again!

**Pull request closed without merging**
