### PR TITLE
Fix race condition on authorization

### PR DESCRIPTION
**Pull request by xAockd**
https://github.com/centrifugal/centrifuge-js/issues/76

### CODE REVIEW

**Comment by FZambia** [comment]
Looks like you forgot to include part of your fix into this pr - `_subscribeXHR` is always null here. Anyway I'll try to extend this to generic case, thanks!

**Comment by xAockd** [comment]
Omg, yes. I'll add it early in the morning

**Comment by FZambia** [comment]
@xAockd could you please check #78 instead - I tried to extrapolate your solution to other cases. Also additionally check client ID to be actual.

**Comment by xAockd** [comment]
@FZambia I've checked your PR. It should solve the issue. But, I think that we have to improve the code and follow DRY principle.
Thanks

**Comment by FZambia** [comment]
Thanks for looking. Yep, agree with you about dry - let's merge it anyway, will appreciate pr fixing code repeatition. I am a bit busy at work these days and work on Swift and investigating possible Java client at moment so any help is much appreciated

**Pull request closed without merging**
