### PR TITLE
The 'channels' should be an array.

### PR DESCRIPTION
**Pull request by Malezha**
Now, if we use the splice requests for access to private channels, it is processed only the last channel other overwritten.

### CODE REVIEW

**Comment by FZambia** [comment]
Hello, could you show request POST data (using browser dev tools for example) which is sent to your backend in case of using `channels`? This is just a name of parameter. Your backend expects `[]` for array parameters?

**Comment by FZambia** [comment]
When I subscribe on two private channels my POST data looks like this:
```
client=bb89d1d3-05af-489a-5325-0a3d999f6744&channels=%24pub&channels=%24public%3Achat
```
Or if replace quoted symbols: 
```
client=bb89d1d3-05af-489a-5325-0a3d999f6744&channels=$pub&channels=$public:chat
```

There are two channels in POST request.

**Comment by Malezha** [comment]
I have a similar request: `client=c756ccf3-bbed-4ec0-7864-698dcf6b0479&channels=%24test1&channels=%24test2`
But on server-side I use PHP and in $_POST I have:
```php
array:2 [
  "client" => "c756ccf3-bbed-4ec0-7864-698dcf6b0479"
  "channels" => "$test2"
]
```

**Comment by FZambia** [comment]
Hmm..this is strange, is this a limitation of PHP? Maybe there is a way to get both channels from request?

**Comment by Malezha** [comment]
Unfortunately, this does not solve the server-side.
If I am not mistaken, that RoR is subject to same illness.

**Comment by Malezha** [comment]
Perhaps you can add alternative option to send the correct names of parameters for PHP.

**Comment by FZambia** [comment]
Just have read about this in internet and it seems that without manually parsing request body it's really impossible. Looked at ROR - it also has the same behaviour. Parsing body is not a good solution so this is a really required fix. I can not figure out how to make this backwards compatible as default name of this parameter must be `channels[]` and having extra option for this name will result in confusion. I'll think about this until tomorrow - but it seems that I accept pull request and write detailed CHANGELOG.

**Comment by FZambia** [comment]
Btw could you share your PHP backend code working with private subscriptions - I will add it to docs?

**Comment by Malezha** [comment]
I can do that, but I use Laravel framework and not sure that my code is not quite obvious without experience with it.

**Comment by FZambia** [comment]
Anyway just for a history - it can help someone else in future.

**Comment by Malezha** [comment]
Ok, where publish it?

**Comment by FZambia** [comment]
Just paste it here I think?

**Comment by Malezha** [comment]
I added [GIST](https://gist.github.com/Malezha/a9bdfbddee15bfd624d4) that if anything, to update it.

**Comment by FZambia** [comment]
Thank you, I merged pull request and made new release.

**Pull request merged**
