### PR TITLE
feat: make browser builds work in WebWorker/SharedWorker contexts

### PR DESCRIPTION
**Pull request by s00d**
This pull request introduces modifications to the Rollup configuration to support the usage of the `centrifuge-js` library in JavaScript environments that do not have access to the `window` global object, such as SharedWorkers, WebWorkers, and Node.js. The need for this change arises from the limitation observed when the compiled library was strictly bound to the `window` object, restricting its usage in broader contexts where a global `window` object may not be present.

By adjusting the Rollup configuration to conditionally check for the existence of a global object and attach the library accordingly, or export it as a module, this update aims to make `centrifuge-js` more versatile. This enhancement allows developers to leverage the library not only in traditional browser environments but also in multi-threaded web applications using WebWorkers, in SharedWorkers for shared state management between multiple browser contexts, and potentially in server-side applications or tools running on Node.js.

Use Cases:
- **WebWorkers & SharedWorkers**: Enhance performance and user experience in web applications by offloading tasks and managing shared state in a background thread, without blocking the main thread.
- **Node.js**: Although initially designed for client-side use, with minor adjustments or for specific use cases, the library could be utilized server-side to manage WebSocket connections or interface with other systems in a Node.js application.

### CODE REVIEW

**Comment by FZambia** [comment]
Hello @s00d ,

`centrifuge-js` does not use `window` object, it uses [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis). So it already works in NodeJS.

Did you observe some issue? Let's start from its description and reproducing steps.

**Comment by s00d** [comment]
[https://unpkg.com/centrifuge@5.0.0/dist/centrifuge.js](here)
image
WebWorkers & SharedWorkers not work in browser

**Comment by FZambia** [comment]
Got it, thanks!

Browsers builds are made with `esbuild`, to make it work I think we need to fix this line:

https://github.com/centrifugal/centrifuge-js/blob/c825ddcc5056a8660c694f6f79fee7c73d2907a4/src/browser.ts#L7

Most probably to:

```
(globalThis as any).Centrifuge = Centrifuge
```

**Comment by s00d** [comment]
I've revised the code as you suggested.

**Comment by FZambia** [comment]
Many thanks!

**Comment by FZambia** [comment]
Released [5.0.2](https://github.com/centrifugal/centrifuge-js/releases/tag/5.0.2) - please check it out

**Comment by s00d** [comment]
Everything works, thank you

**Pull request merged**
