### PR TITLE
Updated README.md for authorization by headers

### PR DESCRIPTION
**Pull request by free6k**
Hi for all!

Updated documentation for proxy backend authorisation (https://centrifugal.github.io/centrifugo/server/proxy/)

### CODE REVIEW

**Comment by FZambia** [comment]
@free6k thanks a lot – could you also mention that this won't work inside a browser?

**Comment by free6k** [comment]
@FZambia In browser API doesn't have the third param options.... only 'url' and 'protocols'. The ws library is isomorphic, but i haven't webpack for test :( I can test later

**Comment by FZambia** [comment]
I mean we should add the text like:

```
If you are building a client for a non-browser environment and want to pass custom headers then you can use the following approach to wrap a WebSocket constructor and let custom options to be used on connection initialization:
```

Also I'd move this to the bottom of the Readme - but I can do this myself later.

**Comment by free6k** [comment]
Thanks, sorry for my bad english :)

**Comment by FZambia** [comment]
@free6k thanks a lot, merged and added minor changes. Also updated feature matrix in c70e75cebf4b15260c2002371ff783d963b3a0de

**Pull request merged**
