### PR TITLE
Added support connect with custom header

### PR DESCRIPTION
**Pull request by free6k**
Hi for all!

Added support connect with custom headers for proxy backend authorisation (https://centrifugal.github.io/centrifugo/server/proxy/)

### CODE REVIEW

**Comment by FZambia** [comment]
Hello, please extend with details.

Browser WebSocket API [does not allow setting custom headers](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket). Which Websocket implementation and in which environment are you using?

**Comment by free6k** [comment]
```
# node -v 
# v12.18.2
```
WebSocket: https://www.npmjs.com/package/ws 7.4.3
my code:
```
var Centrifuge = require("./centrifuge-js/dist/centrifuge");
const WebSocket = require('ws');

var centrifuge = new Centrifuge('wss://localhost:8000/ws/connection/websocket', {
    debug: true,
    websocket: WebSocket,
    connectionHeaders: { Authorization: 'token' }
});
centrifuge.setToken('')

centrifuge.subscribe('u#id', function (context) {
    console.log(JSON.stringify(context))
})

centrifuge.connect()
```

Works is fine and deployed to production )

**Comment by FZambia** [comment]
I mean what is your target environment - as you definitely can't build this for a browser.

My doubt here is that this code is not cross-platform - maybe it's possible to pass a wrapper of WebSocket constructor to centrifuge-js library so all required headers being used. What do you think?

**Comment by free6k** [comment]
Can i add switch cases for browser api and v8? I saw browser api support is hasn't third param
I will think about wrapper of constructor...

**Comment by FZambia** [comment]
> Can i add switch cases for browser api and v8?

I'd prefer to avoid adding such switches as long as possible, I believe that approach with a constructor wrapper should work without introducing any new code into library. We can also add this into readme if it works.

**Comment by free6k** [comment]
Hmm, i just can add documentation in readme.md how connect from nodejs? with help wrap of constructor

**Comment by free6k** [comment]
I can add PR with socket wrapper in Readme.md. Do you need it?

**Comment by FZambia** [comment]
@free6k yes, please. Sorry - I missed your previous comment.

**Comment by free6k** [comment]
I created another PR https://github.com/centrifugal/centrifuge-js/pull/136

**Pull request closed without merging**
