### PR TITLE
Fix reconnect after transport close

### PR DESCRIPTION
**Pull request by oleh-ozimok**

### CODE REVIEW

**Comment by FZambia** [comment]
Hello, thanks! Could you describe which problem this fixes? Why we should not reconnect if transport closed? This can be temporary network glitch for example - so it‘s desired to reconnect

**Comment by oleh-ozimok** [comment]
`

centrifugeProto._disconnectResponse = function (message) {
    if (!errorExists(message)) {
        var shouldReconnect = false;
        if ("reconnect" in message.body) {
            shouldReconnect = message.body["reconnect"];
        }
        var reason = "";
        if ("reason" in message.body) {
            reason = message.body["reason"];
        }
        **this._disconnect(reason, shouldReconnect, true);**
    } else {
        this.trigger('error', [{"message": message}]);
    }
};


centrifugeProto._disconnect = function (reason, shouldReconnect, closeTransport) {
...
    if (closeTransport) {
        **this._transport.close();**
    }
..
}

    this._transport.onclose = function (closeEvent) {
        var reason = "connection closed";
        if (closeEvent && "reason" in closeEvent && closeEvent["reason"]) {
            reason = closeEvent["reason"];
        }
        self._disconnect(reason, **true**, false);
    };


`

**Comment by oleh-ozimok** [comment]
Изучив код могу предложить другое решение - self._disconnect(reason, !self.isDisconnected(), false)

**Comment by FZambia** [comment]
This requires more work to fix than what you suggested. The reason why we can not just stop reconnecting here is that we break client's reconnect after Centrifugo restart or temporary internet connection problem.  Your second solution does not fix API disconnect behaviour. 

At moment when Centrifugo receives `disconnect` API command it just closes client connection. Looks like we need more clever disconnect handling on Centrifugo side - i.e. send `disconnect` response to client first with advice to reconnect or not. And then close connection with force.

**Comment by oleh-ozimok** [comment]
this hot fix work in both cases

```
this._transport.onclose = function (closeEvent) {
        var reason = "connection closed";
        if (closeEvent && "reason" in closeEvent && closeEvent["reason"]) {
            reason = closeEvent["reason"];
        }
        var needReconnect = reason !== "disconnect" ;
        self._disconnect(reason, needReconnect, false);
};
```

**Comment by FZambia** [comment]
Spent some time investigating how to make this better server side - there are some problems with SockJS polling transport that don't let me make disconnect reliable enough. Relying on reason text  will solve the problem - but looks like it has the same problems with polling transports as I came across today. Let me think more about solution..

**Comment by FZambia** [comment]
@oleh-ozimok just pushed fix to master but have not published it to npm yet and have not created tag - could you please check it? I also added tweak for future Centrifugo release to not rely on reason text.

And btw how do you use `disconnect` API command in your app? I am curious because I never used it in my personal apps.

**Comment by oleh-ozimok** [comment]
Disconnecting works correctly. We disconnect users after 20 min of inactivity (we need only real online)

**Comment by FZambia** [comment]
ok, thanks! I'll make release then.

**Pull request closed without merging**
