### PR TITLE
webpack bundler instead of gulp; starting work on code refactoring

### PR DESCRIPTION
**Pull request by Inpassor**
Please, have a look at my changes, and tell me - is it necessary?

### CODE REVIEW

**Comment by FZambia** [comment]
@Inpassor hi, thanks! This looks like a lot of work - you probably better to ask before doing something global like this.

I will find a time to look. Meanwhile could you describe what's a benefit of this migration and are there any backwards incompatible changes (I mean browser support primarily). I understand that gulp is a bit out-dated but it works.

Also a short instruction of how can I create dev build/production release can help me a lot to dive into.

**Comment by Inpassor** [comment]
@FZambia the root cause of why I went into the javascript code is an attempt to make it possible not to JSON-decode the data coming into the channel. I needed this in order to be able to transmit binary data, such as Protobuf.

I also wanted to make the code more up-to-date, rewrite it to the typescript with strict typing and use webpack bundler for builds.

Regarding backward compatibility, everything remains as it is, except that I cut out the .indexOf function polyfill, because this feature is supported by all browsers, starting with IE9.

To make builds just install dependancies ( `npm i` ), then run `npm run build:dev` to make dev build, and `npm run build:prod` to make production build.

**Comment by FZambia** [comment]
@Inpassor btw I was planning to add protobuf and binary websocket to Centrifugo 2 - I have some other ideas apart from that. It would be cool to discuss your experience in Gitter chat or somewhere else (Telegram, Facebook...).

At moment Centrifugo client supports IE < 9 too - so it can't be in current 1.x branch - but pretty OK for next major release.

**Comment by Inpassor** [comment]
@FZambia I am happy to talk about this topic. Do you have Skype? Find the user "inpassor". The only thing is that I do not have the opportunity to receive calls during working hours.

**Pull request closed without merging**
