### PR TITLE
Execute Subscription#subscribe when current subscription exists for channel

### PR DESCRIPTION
**Pull request by andremendonca**

### CODE REVIEW

**Comment by FZambia** [comment]
@andremendonca hello, thanks for pr. Will look at this tomorrow, could you help me to understand what this actually fixes?

**Comment by andremendonca** [comment]
Hey @FZambia, no problem. Let me show a scenario for you:

1. open a chat -> app subscribe channel
2. closed -> app unsubscribe channel
3. open same chat again -> app subscribe channel

at the 3rd interaction, centrifuge-js has a cached instance of the subscription, and instead of creating a new one, it reuse the old one (which is ok). however, different from the 1st interaction, the 3rd interaction never really subscribe the channel, it only returns the cached instance with unsubscribe status and behaviour.

**Comment by FZambia** [comment]
Ok, thanks a lot, think I got it - will try to reproduce this case and merge tomorrow during a day

**Comment by FZambia** [comment]
Merged, thank you! Released 1.3.3 with this fix

**Comment by andremendonca** [comment]
@FZambia most welcome :)
thanks for the hard work with centrifuge

**Pull request merged**
